#!/bin/sh
read -p "Installing required libraries. You may be prompted for a password. [enter]" y
sudo apt-get install python-virtualenv mysql-server libmysqlclient-dev python-dev libjpeg62-dev
echo "Setting up sandboxed Python environment"
virtualenv --no-site-packages ve
echo "Downloading distribute"
ve/bin/python bootstrap.py
read -p "This part may take a while. If it fails with 'connection reset by peer' run ./install-app again. [enter]" y
./bin/buildout -Nv -c dev.cfg
read -p "Create a superuser when prompted. Do not generate default content. [enter]" y
./bin/foundry syncdb
./bin/foundry migrate category
./bin/foundry migrate jmbo
./bin/foundry migrate foundry
./bin/foundry loaddata src/jmbo-foundry/foundry/fixtures/photosizes.json
./bin/foundry loaddata src/jmbo-post/post/fixtures/photosizes.json
./bin/foundry loaddata src/jmbo-gallery/gallery/fixtures/photosizes.json
./bin/foundry loaddata src/jmbo/jmbo/fixtures/photosizes.json
./bin/foundry collectstatic --noinput
echo "You may now start up the site with ./bin/foundry runserver 0.0.0.0:8000"
echo "Browse to http://localhost:8000/ for the public site."
echo "Browse to http://localhost:8000/admin for the admin interface."
