''' Constants that are imported into admin '''

countries = {
    'AF': {'name': 'Afghanistan'},
    'AL': {'name': 'Albania'},
    'DZ': {'name': 'Algeria'},
    'AS': {'name': 'American Samoa '},
    'AD': {'name': 'Andorra'},
    'AO': {'name': 'Angola '},
    'AI': {'name': 'Anguilla '},
    'AQ': {'name': 'Antarctica '},
    'AG': {'name': 'Antigua and Barbuda '},
    'AR': {'name': 'Argentina '},
    'AM': {'name': 'Armenia'},
    'AW': {'name': 'Aruba '},
    'AU': {'name': 'Australia '},
    'AT': {'name': 'Austria'},
    'AZ': {'name': 'Azerbaijan'},
    'BS': {'name': 'Bahamas '},
    'BH': {'name': 'Bahrain'},
    'BD': {'name': 'Bangladesh '},
    'BB': {'name': 'Barbados '},
    'BY': {'name': 'Belarus'},
    'BE': {'name': 'Belgium'},
    'BZ': {'name': 'Belize '},
    'BJ': {'name': 'Benin '},
    'BM': {'name': 'Bermuda '},
    'BT': {'name': 'Bhutan '},
    'BO': {'name': 'Bolivia '},
    'BA': {'name': 'Bosnia and Herzegovina'},
    'BW': {'name': 'Botswana '},
    'BV': {'name': 'Bouvet Island'},
    'BR': {'name': 'Brazil'},
    'BN': {'name': 'Brunei '},
    'BG': {'name': 'Bulgaria '},
    'BF': {'name': 'Burkina Faso '},
    'MM': {'name': 'Burma'},
    'BI': {'name': 'Burundi '},
    'KH': {'name': 'Cambodia'},
    'CM': {'name': 'Cameroon '},
    'CA': {'name': 'Canada '},
    'CV': {'name': 'Cape Verde'},
    'KY': {'name': 'Cayman Islands '},
    'CF': {'name': 'Central Africa '},
    'TD': {'name': 'Chad'},
    'CL': {'name': 'Chile '},
    'CN': {'name': 'China '},
    'CX': {'name': 'Christmas Island (Australia) '},
    'CC': {'name': 'Cocos (Keeling) Islands (Australia) '},
    'CO': {'name': 'Colombia '},
    'KM': {'name': 'Comoros'},
    'CG': {'name': 'Congo '},
    'CD': {'name': 'Congo, the Democratic Republic '},
    'CK': {'name': 'Cook Islands '},
    'CR': {'name': 'Costa Rica '},
    'CI': {'name': 'Cote d\'Ivoire '},
    'HR': {'name': 'Croatia'},
    'CU': {'name': 'Cuba '},
    'CY': {'name': 'Cyprus '},
    'CZ': {'name': 'Czech Republic'},
    'CS': {'name': 'Czechoslovakia '},
    'DK': {'name': 'Denmark'},
    'DJ': {'name': 'Djibouti '},
    'DM': {'name': 'Dominica '},
    'DO': {'name': 'Dominican Republic'},
    'EC': {'name': 'Ecuador '},
    'EG': {'name': 'Egypt'},
    'SV': {'name': 'El Salvador '},
    'GQ': {'name': 'Equatorial Guinea'},
    'ER': {'name': 'Eritrea '},
    'EE': {'name': 'Estonia'},
    'ET': {'name': 'Ethiopia'},
    'FK': {'name': 'Falkland Islands '},
    'FO': {'name': 'Faroe Islands'},
    'FJ': {'name': 'Fiji '},
    'FI': {'name': 'Finland'},
    'FR': {'name': 'France '},
    'GF': {'name': 'French Guiana'},
    'PF': {'name': 'French Polynesia'},
    'GA': {'name': 'Gabon '},
    'GE': {'name': 'Georgia'},
    'DE': {'name': 'Germany'},
    'GH': {'name': 'Ghana '},
    'GI': {'name': 'Gibraltar (UK) '},
    'GR': {'name': 'Greece'},
    'GL': {'name': 'Greenland'},
    'GD': {'name': 'Grenada '},
    'GP': {'name': 'Guadaloupe (France) '},
    'GU': {'name': 'Guam '},
    'GT': {'name': 'Guatemala '},
    'GG': {'name': 'Guernsey'},
    'GN': {'name': 'Guinea'},
    'GW': {'name': 'Guinea-Bissau'},
    'GY': {'name': 'Guyana '},
    'HT': {'name': 'Haiti '},
    'HM': {'name': 'Heard Island and McDonald Islands (Australia) '},
    'VA': {'name': 'Holy See '},
    'HN': {'name': 'Honduras '},
    'HK': {'name': 'Hong Kong (UK) '},
    'HU': {'name': 'Hungary'},
    'IS': {'name': 'Iceland'},
    'IN': {'name': 'India'},
    'IO': {'name': 'Indian Ocean Territory (UK) '},
    'ID': {'name': 'Indonesia '},
    'IR': {'name': 'Iran '},
    'IQ': {'name': 'Iraq '},
    'IE': {'name': 'Ireland'},
    'IM': {'name': 'Isle of Man'},
    'IL': {'name': 'Israel'},
    'IT': {'name': 'Italy'},
    'JM': {'name': 'Jamaica '},
    'JP': {'name': 'Japan '},
    'JE': {'name': 'Jersey'},
    'JO': {'name': 'Jordan'},
    'KZ': {'name': 'Kazakhstan '},
    'KE': {'name': 'Kenya '},
    'KI': {'name': 'Kiribati '},
    'KP': {'name': 'Korea '},
    'XK': {'name': 'Kosovo'},
    'KW': {'name': 'Kuwait'},
    'KG': {'name': 'Kyrgyzstan '},
    'LA': {'name': 'Laos '},
    'LV': {'name': 'Latvia'},
    'LB': {'name': 'Lebanon'},
    'LS': {'name': 'Lesotho '},
    'LR': {'name': 'Liberia '},
    'LY': {'name': 'Libya'},
    'LI': {'name': 'Liechtenstein '},
    'LT': {'name': 'Lithuania'},
    'LU': {'name': 'Luxembourg '},
    'MO': {'name': 'Macau '},
    'MK': {'name': 'Macedonia'},
    'MG': {'name': 'Madagascar '},
    'MW': {'name': 'Malawi '},
    'MY': {'name': 'Malaysia '},
    'MV': {'name': 'Maldives '},
    'ML': {'name': 'Mali '},
    'MT': {'name': 'Malta '},
    'MH': {'name': 'Marshall Islands '},
    'MQ': {'name': 'Martinique (France) '},
    'MR': {'name': 'Mauritania'},
    'MU': {'name': 'Mauritius '},
    'YT': {'name': 'Mayotte (France) '},
    'FX': {'name': 'Metropolitan France '},
    'MX': {'name': 'Mexico '},
    'FM': {'name': 'Micronesia '},
    'MD': {'name': 'Moldova '},
    'MC': {'name': 'Monaco '},
    'MN': {'name': 'Mongolia'},
    'ME': {'name': 'Montenegro'},
    'MS': {'name': 'Montserrat '},
    'MA': {'name': 'Morocco'},
    'MZ': {'name': 'Mozambique'},
    'NA': {'name': 'Namibia '},
    'NR': {'name': 'Nauru '},
    'NP': {'name': 'Nepal '},
    'AN': {'name': 'Netherlands Antilles'},
    'NL': {'name': 'Netherlands'},
    'NC': {'name': 'New Caledonia'},
    'NZ': {'name': 'New Zealand '},
    'NI': {'name': 'Nicaragua '},
    'NE': {'name': 'Niger '},
    'NG': {'name': 'Nigeria '},
    'NU': {'name': 'Niue '},
    'NF': {'name': 'Norfolk Island (Australia) '},
    'ND': {'name': 'Northern Ireland'},
    'MP': {'name': 'Northern Mariana Islands '},
    'NO': {'name': 'Norway'},
    'OM': {'name': 'Oman'},
    'PK': {'name': 'Pakistan '},
    'PW': {'name': 'Palau'},
    'PS': {'name': 'Palestinian Territory, Occupied'},
    'PA': {'name': 'Panama '},
    'PG': {'name': 'Papua New Guinea '},
    'PY': {'name': 'Paraguay '},
    'PE': {'name': 'Peru '},
    'PH': {'name': 'Philippines'},
    'PN': {'name': 'Pitcairn Islands '},
    'PL': {'name': 'Poland'},
    'PT': {'name': 'Portugal '},
    'PR': {'name': 'Puerto Rico '},
    'QA': {'name': 'Qatar '},
    'KR': {'name': 'Republic of Korea (South Korea)'},
    'RS': {'name': 'Republic of Serbia'},
    'RE': {'name': 'Reunion '},
    'RO': {'name': 'Romania '},
    'RU': {'name': 'Russia'},
    'RW': {'name': 'Rwanda '},
    'BL': {'name': 'Saint Barth\xc3\xa9lemy'},
    'SH': {'name': 'Saint Helena (UK) '},
    'KN': {'name': 'Saint Kitts and Nevis '},
    'LC': {'name': 'Saint Lucia '},
    'MF': {'name': 'Saint Martin (French part)'},
    'VC': {'name': 'Saint Vincent and the Grenadines '},
    'PM': {'name': 'Saint-Pierre et Miquelon '},
    'WS': {'name': 'Samoa '},
    'SM': {'name': 'San Marino '},
    'ST': {'name': 'Sao Tome e Principe '},
    'SA': {'name': 'Saudi Arabia'},
    'SN': {'name': 'Senegal '},
    'SC': {'name': 'Seychelles '},
    'SL': {'name': 'Sierra Leone '},
    'SG': {'name': 'Singapore'},
    'SK': {'name': 'Slovakia'},
    'SI': {'name': 'Slovenia'},
    'SB': {'name': 'Solomon Islands '},
    'SO': {'name': 'Somalia '},
    'ZA': {'name': 'South Africa '},
    'GS': {'name': 'South Georgia '},
    'TF': {'name': 'Southern and Antarctic Lands'},
    'SU': {'name': 'Soviet Union'},
    'ES': {'name': 'Spain'},
    'LK': {'name': 'Sri Lanka '},
    'SD': {'name': 'Sudan '},
    'SR': {'name': 'Suriname '},
    'SJ': {'name': 'Svalbard og Jan Mayen '},
    'SZ': {'name': 'Swaziland '},
    'SE': {'name': 'Sweden'},
    'CH': {'name': 'Switzerland'},
    'SY': {'name': 'Syria'},
    'TW': {'name': 'Taiwan'},
    'TJ': {'name': 'Tajikistan'},
    'TZ': {'name': 'Tanzania '},
    'TH': {'name': 'Thailand '},
    'GM': {'name': 'The Gambia '},
    'TP': {'name': 'Timor '},
    'TL': {'name': 'Timor-Leste'},
    'TG': {'name': 'Togo '},
    'TK': {'name': 'Tokelau (New Zealand) '},
    'TO': {'name': 'Tonga '},
    'TT': {'name': 'Trinidad and Tobago '},
    'TN': {'name': 'Tunisia'},
    'TR': {'name': 'Turkey'},
    'TM': {'name': 'Turkmenistan'},
    'TC': {'name': 'Turks and Caicos Islands '},
    'TV': {'name': 'Tuvalu '},
    'UG': {'name': 'Uganda '},
    'UA': {'name': 'Ukraine'},
    'AE': {'name': 'United Arab Emirates '},
    'GB': {'name': 'United Kingdom '},
    'UM': {'name': 'United States Minor Outlying Islands '},
    'US': {'name': 'United States of America '},
    'UY': {'name': 'Uruguay '},
    'UZ': {'name': 'Uzbekistan'},
    'VU': {'name': 'Vanuatu '},
    'VE': {'name': 'Venezuela '},
    'VN': {'name': 'Vietnam'},
    'VG': {'name': 'Virgin Islands (UK) '},
    'VI': {'name': 'Virgin Islands (USA) '},
    'WF': {'name': 'Wallis et Futuna '},
    'EH': {'name': 'Western Sahara '},
    'YE': {'name': 'Yemen '},
    'YU': {'name': 'Yugoslavia '},
    'ZR': {'name': 'Zaire '},
    'ZM': {'name': 'Zambia '},
    'ZW': {'name': 'Zimbabwe '},
    'AX': {'name': '\xc3\x85land Islands'},
}

sorted_countries = [(tup[0], tup[1]['name']) for tup in sorted([item for item in countries.iteritems()], key=lambda i: i[1]['name'])]
