''' Constants that are imported into admin '''

countries = {
    'AF': {'min-age': 0, 'name': 'Afghanistan'},
    'AL': {'min-age': 18, 'name': 'Albania'},
    'DZ': {'min-age': 18, 'name': 'Algeria'},
    'AS': {'name': 'American Samoa'},
    'AD': {'min-age': 18, 'name': 'Andorra'},
    'AO': {'min-age': 18, 'name': 'Angola'},
    'AI': {'name': 'Anguilla'},
    'AQ': {'name': 'Antarctica'},
    'AG': {'min-age': 18, 'name': 'Antigua and Barbuda'},
    'AR': {'min-age': 18, 'name': 'Argentina'},
    'AM': {'min-age': 18, 'name': 'Armenia'},
    'AW': {'name': 'Aruba'},
    'AU': {'min-age': 18, 'name': 'Australia'},
    'AT': {'min-age': 18, 'name': 'Austria'},
    'AZ': {'name': 'Azerbaijan'},
    'BS': {'min-age': 18, 'name': 'Bahamas'},
    'BH': {'min-age': 18, 'name': 'Bahrain'},
    'BD': {'min-age': 0, 'name': 'Bangladesh'},
    'BB': {'min-age': 18, 'name': 'Barbados'},
    'BY': {'min-age': 18, 'name': 'Belarus'},
    'BE': {'min-age': 18, 'name': 'Belgium'},
    'BZ': {'min-age': 18, 'name': 'Belize'},
    'BJ': {'min-age': 18, 'name': 'Benin'},
    'BM': {'name': 'Bermuda'},
    'BT': {'min-age': 18, 'name': 'Bhutan'},
    'BO': {'min-age': 18, 'name': 'Bolivia'},
    'BA': {'min-age': 18, 'name': 'Bosnia and Herzegovina'},
    'BW': {'min-age': 18, 'name': 'Botswana'},
    'BV': {'name': 'Bouvet Island'},
    'BR': {'min-age': 18, 'name': 'Brazil'},
    'BN': {'min-age': 0, 'name': 'Brunei'},
    'BG': {'min-age': 18, 'name': 'Bulgaria'},
    'BF': {'min-age': 18, 'name': 'Burkina Faso'},
    'MM': {'min-age': 18, 'name': 'Burma'},
    'BI': {'min-age': 18, 'name': 'Burundi'},
    'KH': {'min-age': 18, 'name': 'Cambodia'},
    'CM': {'min-age': 18, 'name': 'Cameroon'},
    'CA': {'min-age': 19, 'name': 'Canada'},
    'CV': {'min-age': 18, 'name': 'Cape Verde'},
    'KY': {'name': 'Cayman Islands'},
    'CF': {'min-age': 18, 'name': 'Central Africa'},
    'TD': {'min-age': 18, 'name': 'Chad'},
    'CL': {'min-age': 18, 'name': 'Chile'},
    'CN': {'min-age': 18, 'name': 'China'},
    'CX': {'name': 'Christmas Island (Australia)'},
    'CC': {'name': 'Cocos (Keeling) Islands (Australia)'},
    'CO': {'min-age': 18, 'name': 'Colombia'},
    'KM': {'min-age': 18, 'name': 'Comoros'},
    'CG': {'name': 'Congo'},
    'CD': {'min-age': 18, 'name': 'Congo, the Democratic Republic'},
    'CK': {'min-age': 18, 'name': 'Cook Islands'},
    'CR': {'min-age': 18, 'name': 'Costa Rica'},
    'CI': {'min-age': 18, 'name': "Cote d'Ivoire"},
    'HR': {'min-age': 18, 'name': 'Croatia'},
    'CU': {'name': 'Cuba'},
    'CY': {'min-age': 18, 'name': 'Cyprus'},
    'CZ': {'min-age': 18, 'name': 'Czech Republic'},
    'CS': {'name': 'Czechoslovakia'},
    'DK': {'min-age': 18, 'name': 'Denmark'},
    'DJ': {'min-age': 18, 'name': 'Djibouti'},
    'DM': {'min-age': 18, 'name': 'Dominica'},
    'DO': {'min-age': 18, 'name': 'Dominican Republic'},
    'EC': {'min-age': 18, 'name': 'Ecuador'},
    'EG': {'min-age': 0, 'name': 'Egypt'},
    'SV': {'min-age': 18, 'name': 'El Salvador'},
    'GQ': {'min-age': 18, 'name': 'Equatorial Guinea'},
    'ER': {'min-age': 18, 'name': 'Eritrea'},
    'EE': {'min-age': 18, 'name': 'Estonia'},
    'ET': {'min-age': 0, 'name': 'Ethiopia'},
    'FK': {'name': 'Falkland Islands'},
    'FO': {'name': 'Faroe Islands'},
    'FJ': {'min-age': 18, 'name': 'Fiji'},
    'FI': {'min-age': 0, 'name': 'Finland'},
    'FR': {'min-age': 18, 'name': 'France'},
    'GF': {'name': 'French Guiana'},
    'PF': {'name': 'French Polynesia'},
    'GA': {'min-age': 18, 'name': 'Gabon'},
    'GE': {'min-age': 18, 'name': 'Georgia'},
    'DE': {'min-age': 18, 'name': 'Germany'},
    'GH': {'min-age': 18, 'name': 'Ghana'},
    'GI': {'name': 'Gibraltar (UK)'},
    'GR': {'min-age': 18, 'name': 'Greece'},
    'GL': {'min-age': 18, 'name': 'Greenland'},
    'GD': {'min-age': 18, 'name': 'Grenada'},
    'GP': {'name': 'Guadaloupe (France)'},
    'GU': {'name': 'Guam'},
    'GT': {'min-age': 18, 'name': 'Guatemala'},
    'GG': {'name': 'Guernsey'},
    'GN': {'name': 'Guinea'},
    'GW': {'min-age': 18, 'name': 'Guinea-Bissau'},
    'GY': {'min-age': 18, 'name': 'Guyana'},
    'HT': {'min-age': 18, 'name': 'Haiti'},
    'HM': {'name': 'Heard Island and McDonald Islands (Australia)'},
    'VA': {'name': 'Holy See'},
    'HN': {'min-age': 21, 'name': 'Honduras'},
    'HK': {'min-age': 18, 'name': 'Hong Kong (UK)'},
    'HU': {'min-age': 18, 'name': 'Hungary'},
    'IS': {'min-age': 0, 'name': 'Iceland'},
    'IN': {'min-age': 18, 'name': 'India'},
    'IO': {'min-age': 18, 'name': 'Indian Ocean Territory (UK)'},
    'ID': {'min-age': 21, 'name': 'Indonesia'},
    'IR': {'min-age': 0, 'name': 'Iran'},
    'IQ': {'min-age': 0, 'name': 'Iraq'},
    'IE': {'min-age': 18, 'name': 'Ireland'},
    'IM': {'name': 'Isle of Man'},
    'IL': {'min-age': 18, 'name': 'Israel'},
    'IT': {'min-age': 18, 'name': 'Italy'},
    'JM': {'min-age': 18, 'name': 'Jamaica'},
    'JP': {'min-age': 20, 'name': 'Japan'},
    'JE': {'name': 'Jersey'},
    'JO': {'min-age': 0, 'name': 'Jordan'},
    'KZ': {'min-age': 0, 'name': 'Kazakhstan'},
    'KE': {'min-age': 18, 'name': 'Kenya'},
    'KI': {'name': 'Kiribati'},
    'KP': {'min-age': 18, 'name': 'Korea'},
    'XK': {'name': 'Kosovo'},
    'KW': {'min-age': 0, 'name': 'Kuwait'},
    'KG': {'min-age': 0, 'name': 'Kyrgyzstan'},
    'LA': {'min-age': 18, 'name': 'Laos'},
    'LV': {'min-age': 18, 'name': 'Latvia'},
    'LB': {'min-age': 18, 'name': 'Lebanon'},
    'LS': {'min-age': 18, 'name': 'Lesotho'},
    'LR': {'min-age': 18, 'name': 'Liberia'},
    'LY': {'min-age': 0, 'name': 'Libya'},
    'LI': {'min-age': 18, 'name': 'Liechtenstein'},
    'LT': {'min-age': 18, 'name': 'Lithuania'},
    'LU': {'min-age': 18, 'name': 'Luxembourg'},
    'MO': {'name': 'Macau'},
    'MK': {'min-age': 18, 'name': 'Macedonia'},
    'MG': {'min-age': 18, 'name': 'Madagascar'},
    'MW': {'min-age': 18, 'name': 'Malawi'},
    'MY': {'min-age': 18, 'name': 'Malaysia'},
    'MV': {'min-age': 18, 'name': 'Maldives'},
    'ML': {'min-age': 18, 'name': 'Mali'},
    'MT': {'min-age': 18, 'name': 'Malta'},
    'MH': {'min-age': 18, 'name': 'Marshall Islands'},
    'MQ': {'name': 'Martinique (France)'},
    'MR': {'min-age': 18, 'name': 'Mauritania'},
    'MU': {'min-age': 18, 'name': 'Mauritius'},
    'YT': {'name': 'Mayotte (France)'},
    'FX': {'name': 'Metropolitan France'},
    'MX': {'min-age': 18, 'name': 'Mexico'},
    'FM': {'min-age': 18, 'name': 'Micronesia'},
    'MD': {'min-age': 18, 'name': 'Moldova'},
    'MC': {'min-age': 18, 'name': 'Monaco'},
    'MN': {'min-age': 18, 'name': 'Mongolia'},
    'ME': {'name': 'Montenegro'},
    'MS': {'name': 'Montserrat'},
    'MA': {'min-age': 18, 'name': 'Morocco'},
    'MZ': {'min-age': 18, 'name': 'Mozambique'},
    'NA': {'min-age': 18, 'name': 'Namibia'},
    'NR': {'min-age': 18, 'name': 'Nauru'},
    'NP': {'min-age': 0, 'name': 'Nepal'},
    'NL': {'min-age': 18, 'name': 'Netherlands'},
    'AN': {'name': 'Netherlands Antilles'},
    'NC': {'name': 'New Caledonia'},
    'NZ': {'min-age': 18, 'name': 'New Zealand'},
    'NI': {'min-age': 18, 'name': 'Nicaragua'},
    'NE': {'name': 'Niger'},
    'NG': {'min-age': 18, 'name': 'Nigeria'},
    'NU': {'name': 'Niue'},
    'NF': {'name': 'Norfolk Island (Australia)'},
    'ND': {'name': 'Northern Ireland'},
    'MP': {'name': 'Northern Mariana Islands'},
    'NO': {'min-age': 0, 'name': 'Norway'},
    'OM': {'min-age': 21, 'name': 'Oman'},
    'PK': {'min-age': 0, 'name': 'Pakistan'},
    'PW': {'min-age': 18, 'name': 'Palau'},
    'PS': {'name': 'Palestinian Territory, Occupied'},
    'PA': {'min-age': 18, 'name': 'Panama'},
    'PG': {'min-age': 18, 'name': 'Papua New Guinea'},
    'PY': {'min-age': 20, 'name': 'Paraguay'},
    'PE': {'min-age': 18, 'name': 'Peru'},
    'PH': {'min-age': 18, 'name': 'Philippines'},
    'PN': {'name': 'Pitcairn Islands'},
    'PL': {'min-age': 0, 'name': 'Poland'},
    'PT': {'min-age': 18, 'name': 'Portugal'},
    'PR': {'name': 'Puerto Rico'},
    'QA': {'min-age': 18, 'name': 'Qatar'},
    'KR': {'min-age': 18, 'name': 'Republic of Korea (South Korea)'},
    'RS': {'name': 'Republic of Serbia'},
    'RE': {'name': 'Reunion'},
    'RO': {'min-age': 18, 'name': 'Romania'},
    'RU': {'min-age': 18, 'name': 'Russia'},
    'RW': {'min-age': 18, 'name': 'Rwanda'},
    'BL': {'name': 'Saint Barth\xc3\xa9lemy'},
    'SH': {'name': 'Saint Helena (UK)'},
    'KN': {'min-age': 18, 'name': 'Saint Kitts and Nevis'},
    'LC': {'min-age': 18, 'name': 'Saint Lucia'},
    'MF': {'name': 'Saint Martin (French part)'},
    'VC': {'min-age': 21, 'name': 'Saint Vincent and the Grenadines'},
    'PM': {'name': 'Saint-Pierre et Miquelon'},
    'WS': {'min-age': 18, 'name': 'Samoa'},
    'SM': {'min-age': 18, 'name': 'San Marino'},
    'ST': {'min-age': 18, 'name': 'Sao Tome e Principe'},
    'SA': {'min-age': 0, 'name': 'Saudi Arabia'},
    'SN': {'min-age': 18, 'name': 'Senegal'},
    'SC': {'name': 'Seychelles'},
    'SL': {'name': 'Sierra Leone'},
    'SG': {'min-age': 18, 'name': 'Singapore'},
    'SK': {'min-age': 18, 'name': 'Slovakia'},
    'SI': {'min-age': 18, 'name': 'Slovenia'},
    'SB': {'min-age': 18, 'name': 'Solomon Islands'},
    'SO': {'min-age': 18, 'name': 'Somalia'},
    'ZA': {'min-age': 18, 'name': 'South Africa'},
    'GS': {'name': 'South Georgia'},
    'TF': {'name': 'Southern and Antarctic Lands'},
    'SU': {'name': 'Soviet Union'},
    'ES': {'min-age': 18, 'name': 'Spain'},
    'LK': {'min-age': 18, 'name': 'Sri Lanka'},
    'SD': {'min-age': 0, 'name': 'Sudan'},
    'SR': {'name': 'Suriname'},
    'SJ': {'name': 'Svalbard og Jan Mayen'},
    'SZ': {'min-age': 18, 'name': 'Swaziland'},
    'SE': {'min-age': 0, 'name': 'Sweden'},
    'CH': {'min-age': 18, 'name': 'Switzerland'},
    'SY': {'min-age': 0, 'name': 'Syria'},
    'TW': {'min-age': 18, 'name': 'Taiwan'},
    'TJ': {'name': 'Tajikistan'},
    'TZ': {'min-age': 18, 'name': 'Tanzania'},
    'TH': {'min-age': 20, 'name': 'Thailand'},
    'GM': {'min-age': 18, 'name': 'The Gambia'},
    'TP': {'name': 'Timor'},
    'TL': {'name': 'Timor-Leste'},
    'TG': {'name': 'Togo'},
    'TK': {'name': 'Tokelau (New Zealand)'},
    'TO': {'min-age': 18, 'name': 'Tonga'},
    'TT': {'min-age': 18, 'name': 'Trinidad and Tobago'},
    'TN': {'min-age': 18, 'name': 'Tunisia'},
    'TR': {'min-age': 18, 'name': 'Turkey'},
    'TM': {'min-age': 0, 'name': 'Turkmenistan'},
    'TC': {'name': 'Turks and Caicos Islands'},
    'TV': {'name': 'Tuvalu'},
    'UG': {'name': 'Uganda'},
    'UA': {'min-age': 18, 'name': 'Ukraine'},
    'AE': {'min-age': 21, 'name': 'United Arab Emirates'},
    'GB': {'min-age': 18, 'name': 'United Kingdom'},
    'UM': {'min-age': 21, 'name': 'United States Minor Outlying Islands'},
    'US': {'min-age': 21, 'name': 'United States of America'},
    'UY': {'name': 'Uruguay'},
    'UZ': {'min-age': 0, 'name': 'Uzbekistan'},
    'VU': {'min-age': 18, 'name': 'Vanuatu'},
    'VE': {'min-age': 18, 'name': 'Venezuela'},
    'VN': {'min-age': 18, 'name': 'Vietnam'},
    'VG': {'name': 'Virgin Islands (UK)'},
    'VI': {'name': 'Virgin Islands (USA)'},
    'WF': {'name': 'Wallis et Futuna'},
    'EH': {'name': 'Western Sahara'},
    'YE': {'min-age': 0, 'name': 'Yemen'},
    'YU': {'name': 'Yugoslavia'},
    'ZR': {'name': 'Zaire'},
    'ZM': {'min-age': 18, 'name': 'Zambia'},
    'ZW': {'min-age': 18, 'name': 'Zimbabwe'},
    'AX': {'name': '\xc3\x85land Islands'},
}

sorted_countries = [(tup[0], tup[1]['name']) for tup in sorted([item for item in countries.iteritems()], key=lambda i: i[1]['name'])]
